# Canaveral Multiplatform Build Workflow
# This workflow builds iOS and Android apps in parallel using Canaveral
# Ideal for Flutter, React Native, or other cross-platform frameworks
#
# Required secrets: See build-ios.yml and build-android.yml

name: Build Multiplatform

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

env:
  # Framework detection (auto-detected if not set)
  # CANAVERAL_FRAMEWORK: flutter

  # iOS configuration
  CANAVERAL_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
  CANAVERAL_BUNDLE_ID: ${{ vars.IOS_BUNDLE_ID }}

  # Match configuration
  MATCH_GIT_URL: ${{ vars.MATCH_GIT_URL }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  detect:
    name: Detect Framework
    runs-on: ubuntu-latest
    outputs:
      framework: ${{ steps.detect.outputs.framework }}
      has_ios: ${{ steps.detect.outputs.has_ios }}
      has_android: ${{ steps.detect.outputs.has_android }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Detect Framework
        id: detect
        run: |
          RESULT=$(canaveral status --format json)
          FRAMEWORK=$(echo "$RESULT" | jq -r '.framework // "unknown"')
          HAS_IOS=$(echo "$RESULT" | jq -r '.platforms.ios // false')
          HAS_ANDROID=$(echo "$RESULT" | jq -r '.platforms.android // false')

          echo "framework=$FRAMEWORK" >> $GITHUB_OUTPUT
          echo "has_ios=$HAS_IOS" >> $GITHUB_OUTPUT
          echo "has_android=$HAS_ANDROID" >> $GITHUB_OUTPUT

          echo "Detected: framework=$FRAMEWORK, ios=$HAS_IOS, android=$HAS_ANDROID"

  build-ios:
    name: Build iOS
    needs: detect
    if: needs.detect.outputs.has_ios == 'true'
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Flutter
        if: needs.detect.outputs.framework == 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Setup Node.js
        if: needs.detect.outputs.framework == 'react-native' || needs.detect.outputs.framework == 'expo'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
          elif [ -f "package.json" ]; then
            npm ci
          fi

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Sync Certificates
        run: |
          canaveral match sync \
            --profile-type ${{ inputs.build_type == 'release' && 'appstore' || 'development' }} \
            --readonly

      - name: Build iOS
        run: |
          canaveral build \
            --platform ios \
            --profile ${{ inputs.build_type || 'debug' }} \
        env:
          CI: true

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-${{ inputs.build_type || 'debug' }}
          path: |
            build/ios/*.ipa
            build/ios/*.app.dSYM.zip
          if-no-files-found: error
          retention-days: 14

  build-android:
    name: Build Android
    needs: detect
    if: needs.detect.outputs.has_android == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        if: needs.detect.outputs.framework == 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Setup Node.js
        if: needs.detect.outputs.framework == 'react-native' || needs.detect.outputs.framework == 'expo'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
          elif [ -f "package.json" ]; then
            npm ci
          fi

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Decode Keystore
        if: inputs.build_type == 'release'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Build Android
        run: |
          canaveral build \
            --platform android \
            --profile ${{ inputs.build_type || 'debug' }} \
        env:
          CI: true
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ inputs.build_type || 'debug' }}
          path: |
            build/android/*.apk
            build/android/*.aab
          if-no-files-found: error
          retention-days: 14

  release:
    name: Create Release
    needs: [build-ios, build-android]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-release
          path: artifacts/ios

      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-release
          path: artifacts/android

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/ios/*.ipa
            artifacts/android/*.apk
            artifacts/android/*.aab
          generate_release_notes: true
          draft: true
