# Canaveral Release Workflow
# This workflow creates a new release using Canaveral
# Handles version bumping, changelog generation, and store uploads
#
# Trigger: Create a new release via GitHub UI or dispatch workflow

name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      deploy_ios:
        description: 'Deploy to App Store'
        required: true
        type: boolean
        default: true
      deploy_android:
        description: 'Deploy to Google Play'
        required: true
        type: boolean
        default: true
      dry_run:
        description: 'Dry run (no actual release)'
        required: false
        type: boolean
        default: false

env:
  # Apple credentials
  CANAVERAL_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
  MATCH_GIT_URL: ${{ vars.MATCH_GIT_URL }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

  # Google Play credentials
  GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}

jobs:
  version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Calculate Next Version
        id: version
        run: |
          VERSION=$(canaveral version --release-type ${{ inputs.bump_type }} --format json | jq -r '.next')

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "Next version: $VERSION"

      - name: Generate Changelog
        id: changelog
        run: |
          CHANGELOG=$(canaveral changelog)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-ios:
    name: Build iOS Release
    needs: version
    if: inputs.deploy_ios
    runs-on: macos-14
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
          fi

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Sync Certificates
        run: canaveral match sync --profile-type appstore --readonly

      - name: Build iOS Release
        run: |
          canaveral build \
            --platform ios \
            --profile release \
            --version ${{ needs.version.outputs.version }}
        env:
          CI: true

      - name: Upload to TestFlight
        if: ${{ !inputs.dry_run }}
        run: |
          canaveral test-flight upload build/ios/*.ipa \
            --changelog "${{ needs.version.outputs.changelog }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/*.ipa
          retention-days: 30

  build-android:
    name: Build Android Release
    needs: version
    if: inputs.deploy_android
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
          fi

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Build Android Release
        run: |
          canaveral build \
            --platform android \
            --profile release \
            --version ${{ needs.version.outputs.version }}
        env:
          CI: true
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload to Google Play
        if: ${{ !inputs.dry_run }}
        run: |
          canaveral publish google-play build/android/*.aab \
            --package-name "$ANDROID_PACKAGE_NAME" \
            --service-account play-service-account.json \
            --track internal

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/android/*.aab
          retention-days: 30

  create-release:
    name: Create GitHub Release
    needs: [version, build-ios, build-android]
    if: always() && !inputs.dry_run && (needs.build-ios.result == 'success' || needs.build-android.result == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Canaveral
        run: |
          curl -fsSL https://get.canaveral.dev | sh
          echo "$HOME/.canaveral/bin" >> $GITHUB_PATH

      - name: Create Release
        run: |
          canaveral release \
            --version ${{ needs.version.outputs.version }} \
            --yes

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.tag }}
          name: Release ${{ needs.version.outputs.version }}
          body: ${{ needs.version.outputs.changelog }}
          files: |
            artifacts/ios-release/*.ipa
            artifacts/android-release/*.aab
          draft: false
